/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface WcNavbar {}
  interface WcNavbarAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'WcNavbar': Components.WcNavbar;
  }

  interface StencilIntrinsicElements {
    'wc-navbar': Components.WcNavbarAttributes;
  }


  interface HTMLWcNavbarElement extends Components.WcNavbar, HTMLStencilElement {}
  var HTMLWcNavbarElement: {
    prototype: HTMLWcNavbarElement;
    new (): HTMLWcNavbarElement;
  };

  interface HTMLElementTagNameMap {
    'wc-navbar': HTMLWcNavbarElement
  }

  interface ElementTagNameMap {
    'wc-navbar': HTMLWcNavbarElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
