/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface WcNavItem {
    'href': string;
    'target': string;
  }
  interface WcNavItemAttributes extends StencilHTMLAttributes {
    'href'?: string;
    'target'?: string;
  }

  interface WcNavbar {}
  interface WcNavbarAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'WcNavItem': Components.WcNavItem;
    'WcNavbar': Components.WcNavbar;
  }

  interface StencilIntrinsicElements {
    'wc-nav-item': Components.WcNavItemAttributes;
    'wc-navbar': Components.WcNavbarAttributes;
  }


  interface HTMLWcNavItemElement extends Components.WcNavItem, HTMLStencilElement {}
  var HTMLWcNavItemElement: {
    prototype: HTMLWcNavItemElement;
    new (): HTMLWcNavItemElement;
  };

  interface HTMLWcNavbarElement extends Components.WcNavbar, HTMLStencilElement {}
  var HTMLWcNavbarElement: {
    prototype: HTMLWcNavbarElement;
    new (): HTMLWcNavbarElement;
  };

  interface HTMLElementTagNameMap {
    'wc-nav-item': HTMLWcNavItemElement
    'wc-navbar': HTMLWcNavbarElement
  }

  interface ElementTagNameMap {
    'wc-nav-item': HTMLWcNavItemElement;
    'wc-navbar': HTMLWcNavbarElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
